// Export pages
export '/ui_screens/registration_package/login_screen/login_screen_widget.dart'
    show LoginScreenWidget;
export '/ui_screens/registration_package/registraation_page/registraation_page_widget.dart'
    show RegistraationPageWidget;
export '/ui_screens/nav_pakege/home_screen/home_screen_widget.dart'
    show HomeScreenWidget;
export '/ui_screens/nav_home_pakage/shop_page/shop_page_widget.dart'
    show ShopPageWidget;
export '/ui_screens/registration_package/splash_page/splash_page_widget.dart'
    show SplashPageWidget;
export '/ui_screens/nav_pakege/car_page/car_page_widget.dart'
    show CarPageWidget;
export '/ui_screens/settings_screens/about_app_page/about_app_page_widget.dart'
    show AboutAppPageWidget;
export '/ui_screens/nav_home_pakage/car_model_page/car_model_page_widget.dart'
    show CarModelPageWidget;
export '/ui_screens/app_bar_packages/my_profile_page/my_profile_page_widget.dart'
    show MyProfilePageWidget;
export '/ui_screens/app_bar_packages/personal_information_page/personal_information_page_widget.dart'
    show PersonalInformationPageWidget;
export '/ui_screens/app_bar_packages/edit_profile_page/edit_profile_page_widget.dart'
    show EditProfilePageWidget;
export '/ui_screens/app_bar_packages/my_order_page/my_order_page_widget.dart'
    show MyOrderPageWidget;
export '/ui_screens/nav_home_pakage/news_page/news_page_widget.dart'
    show NewsPageWidget;
export '/ui_screens/nav_home_pakage/news_details_page/news_details_page_widget.dart'
    show NewsDetailsPageWidget;
export '/ui_screens/app_bar_packages/edit_password_page/edit_password_page_widget.dart'
    show EditPasswordPageWidget;
export '/ui_screens/settings_screens/settings_page/settings_page_widget.dart'
    show SettingsPageWidget;
export '/ui_screens/nav_home_pakage/maintenance_page/maintenance_page_widget.dart'
    show MaintenancePageWidget;
export '/ui_screens/nav_home_pakage/regular_page/regular_page_widget.dart'
    show RegularPageWidget;
export '/ui_screens/nav_home_pakage/repair_page/repair_page_widget.dart'
    show RepairPageWidget;
export '/ui_screens/nav_home_pakage/shop_details_page/shop_details_page_widget.dart'
    show ShopDetailsPageWidget;
export '/ui_screens/nav_home_pakage/item_details_page/item_details_page_widget.dart'
    show ItemDetailsPageWidget;
export '/ui_screens/nav_home_pakage/location_page/location_page_widget.dart'
    show LocationPageWidget;
